{
 "title": "bermann",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "30s,1m,5m,10m,30m,1h" },
   { "name": "host", "query": { "query": "label_values(apache)" } }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 10, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "collectd_apache_apache_scoreboard{apache=\"10.10.2.100\", type=\"closing\"}"
      }
     ]
    }
   ]
  },
  { "title": "mod_status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total bytes served",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_apache_bytes_total{apache=\"$host\"}",
     "legendFormat": "Total bytes served by server $host"
    }
   ]
  },
  {
   "title": "Queries received by the server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_apache_requests_total{apache=\"$host\"}",
     "legendFormat": "Total queries to server $host"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses",
   "type": "graph",
   "description": "Apache scoreboard statuses",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"closing\"}",
     "legendFormat": "Closing connection"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"dnslookup\"}",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"finishing\"}",
     "legendFormat": "Gracefully finishing"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"idle_cleanup\"}",
     "legendFormat": "Idle cleanup of worker,"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"keepalive\"}",
     "legendFormat": "Keepalive (read)"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"logging\"}",
     "legendFormat": "Logging"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"open\"}",
     "legendFormat": "Open slot with no current process"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"reading\"}",
     "legendFormat": "Reading Request"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"sending\"}",
     "legendFormat": "Sending Reply"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"starting\"}",
     "legendFormat": "Starting up"
    },
    {
     "expr": "collectd_apache_apache_scoreboard{apache=\"$host\", type=\"waiting\"}",
     "legendFormat": "Waiting for Connection"
    }
   ]
  },
  { "title": "access_log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "HTTP 2xx / Interval",
   "type": "stat",
   "description": "2xx Success",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time({host=\"$host\"} |~ \" 20[0-9] \" != \"mod_status\" != \"nagios\" [$interval])"
    }
   ]
  },
  {
   "title": "4xx and 2xx for an interval of time",
   "type": "timeseries",
   "description": "4xx and 2xx for an interval of time",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 21 },
   "targets": [
    {
     "expr": "count_over_time({host=\"$host\"} |~ \" 20[0-9] \" != \"mod_status\" != \"nagios\" [$interval])",
     "legendFormat": "2xx"
    },
    {
     "expr": "count_over_time({host=\"$host\"} |~ \" 4[0-5][0-9] \" != \"mod_status\" != \"nagios\" [$interval])",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "HTTP 3xx / Interval",
   "type": "stat",
   "description": "3xx Success",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time({host=\"$host\"} |~ \" 30[0-8] \" != \"mod_status\" != \"nagios\" [$interval])"
    }
   ]
  },
  {
   "title": "HTTP 4xx / Interval",
   "type": "stat",
   "description": "4xx Success",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time({host=\"$host\"} |~ \" 4[0-5][0-9] \" != \"mod_status\" != \"nagios\" [$interval])"
    }
   ]
  },
  {
   "title": "HTTP 5xx / Interval",
   "type": "stat",
   "description": "5xx Success",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time({host=\"$host\"} |~ \" 5[0-2][0-9] \" != \"mod_status\" != \"nagios\" [$interval])"
    }
   ]
  },
  {
   "title": "Total logs 4xx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{host=\"$host\"} |~ \" 4[0-5][0-9] \" != \"mod_status\" != \"nagios\""
    }
   ]
  }
 ]
}